name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up goose
        uses: mscno/setup-goose@v1

      - name: Run goose
        run: goose up

      - name: Build Production
        run: ./scripts/buildprod.sh

      - name: Run db migration
        run: ./scripts/migrateup.sh

      - name: GCP Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Build Docker image and push to Google Artifact Registry
        run: gcloud builds submit --tag asia-northeast3-docker.pkg.dev/notely-440409/notely-ar-repo/ktkennyc/notely .

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image asia-northeast3-docker.pkg.dev/notely-440409/notely-ar-repo/ktkennyc/notely --region asia-northeast3 --allow-unauthenticated --project notely-440409 --max-instances=4

      - name: Check code diff
        run: git diff
